### ISSUE TITLE
Rspec tests are failing 

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#540]
Hi @owen2345,
After merging latest fixes rspec test cases are failing with below errors, all testcases are failing with same error.
```
2) the Themes Widgets list
     Got 0 failures and 2 other errors:

     2.1) Failure/Error: admin_sign_in
          
          NameError:
            undefined local variable or method `screenshot_and_save_page' for #<RSpec::ExampleGroups::TheThemes:0x007fca132e0088>
          # /Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0/bundler/gems/camaleon-cms-965413185e80/spec/support/common.rb:31:in `admin_sign_in'
          # /Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0/bundler/gems/camaleon-cms-965413185e80/spec/features/widgets_spec.rb:6:in `block (2 levels) in <top (required)>'

     2.2) Failure/Error: Unable to find (sass) to read failed line
          
          ActionView::Template::Error:
            Invalid CSS after "	background:": expected "{", was "url(data:image/..."
          # (sass):14282
          # /Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0/gems/sass-3.4.22/lib/sass/scss/parser.rb:1189:in `expected'
          # /Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0/gems/sass-3.4.22/lib/sass/scss/parser.rb:1125:in `expected'
```

**Comment by owen2345** [comment]
Hi @mazharoddin,
Please configure your test following these steps (poltergeist):
https://github.com/owen2345/camaleon-cms#testing
![screen shot 2016-11-25 at 07 19 03](https://cloud.githubusercontent.com/assets/1148415/20626899/0b43a014-b2f3-11e6-9860-fcfb715b2551.png)

Regards,

**Comment by FlowerWrong** [comment]
So disappoint, phantomjs 1.9.2 and 1.9.8 not work for my mac. `segmentation fault` error.
```bash
wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/phantomjs/phantomjs-1.9.2-macosx.zip
wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
```

And new version 2.1.1 of phantomjs have 19 test not pass.

```
Finished in 2 minutes 30.8 seconds (files took 3.15 seconds to load)
78 examples, 19 failures

Failed examples:

rspec ./spec/decorators/post_type_spec.rb:4 # PostTypeDecorator group url
rspec ./spec/decorators/post_type_spec.rb:9 # PostTypeDecorator public url
rspec ./spec/features/comments_spec.rb:5 # the Comments Add Comment
rspec ./spec/features/comments_spec.rb:18 # the Comments list comments post
rspec ./spec/features/contact_form_spec.rb:5 # the Contact Form create new contact form
rspec ./spec/features/contact_form_spec.rb:32 # the Contact Form check contact submitters
rspec ./spec/features/contact_form_spec.rb:43 # the Contact Form delete contact form
rspec ./spec/features/custom_fields_spec.rb:5 # the Custom Fields Custom fields list
rspec ./spec/features/media_spec.rb:5 # the Media list media
rspec ./spec/features/menus_spec.rb:5 # the Menus Menus list
rspec ./spec/features/pages_spec.rb:5 # the signin process create new page
rspec ./spec/features/pages_spec.rb:21 # the signin process create edit page
rspec ./spec/features/posts_spec.rb:5 # the signin process create new post
rspec ./spec/features/posts_spec.rb:21 # the signin process create edit post
rspec ./spec/features/sites_spec.rb:36 # the Sites Site destroy
rspec ./spec/features/tags_spec.rb:16 # the signin process create edit tag
rspec ./spec/helpers/email_helper_spec.rb:6 # CamaleonCms::EmailHelper #send_email (old way) returns empty
rspec ./spec/helpers/email_helper_spec.rb:12 # CamaleonCms::EmailHelper #send_email (new way) returns empty
rspec ./spec/routing/post_type_routes_spec.rb:4 # routes for Post Types routes for /test-post-type
```
😞
