### ISSUE TITLE
undefined local variable or method `cama_root_url' with rails 5.0.

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#473]
Hi @owen2345 ,
I am getting below error after upgrading to 5.0. this error I am seeing if my existing site has custom root route defined, this was working fine with 4.2.7 version. I never had this issue with any other rails version.
```
undefined local variable or method `cama_root_url' for #<CamaleonCms::FrontendController:0x007fd7e6306f90> Did you mean? cama_robots_url cama_post_url cama_rss_url cama_admin_forgot_url cama_error_url cama_category_en_url cama_search_url cama_logout_user cama_post_type_7_url cama_post_tag_en_url cama_post_type_2_url cama_robots_path cama_captcha_url cama_sitemap_url cama_ajax_url

  def ecommerce_front_before_load
    @ecommerce_post_type = current_site.post_types.where(slug: 'commerce').first.decorate
    @ecommerce_bredcrumb = [].push(["Home", cama_root_url])
  end

  def ecommerce_admin_before_load

/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0.0/bundler/gems/camaleon-ecommerce-a8543f617be2/app/helpers/plugins/ecommerce/ecommerce_helper.rb:16:in `ecommerce_front_before_load'
```
I have below root route defined in my config/routes.rb file
```
 root  'high_voltage/pages#show', id: 'home'
```
Without above line camaleon_cms root route becomes the home page, but I wanted to have static home page provided by the high_voltage gem.
Can you please let me know how I can resolve it.

**Comment by owen2345** [comment]
@mazharoddin,
I fixed the problem, please test using the git version before to publish a new gem version.
Regards,

**Comment by mazharoddin** [comment]
Hi @owen2345,
Yeah site root issues is got resolved now, thanks. But seeing this error after pulling latest code.
```
pp/apps/themes/efashion/views/layouts/_header.html.erb where line #32 raised:

undefined local variable or method `current_user' for #<#<Class:0x007f9c7be0c8c8>:0x007f9c7be584f8>
Did you mean?  current_site
					<div class="cart box_1">
	                    <% if cama_current_user.present? %>
	                        <% cart = current_site.carts.set_user(current_user).first_or_create(name: "Cart by #{current_user.id}").decorate %>
						<a href="<%= plugins_ecommerce_checkout_cart_path %>">
						<h3> <div class="total">
							<span class="simpleCart_total"><%= cart.the_price  %></span></div>
app/apps/themes/efashion/views/layouts/_header.html.erb:32:in `_app_apps_themes_efashion_views_layouts__header_html_erb__1733713776537051105_70155033032040'
app/apps/themes/efashion/views/layouts/index.html.erb:18:in `_app_apps_themes_efashion_views_layouts_index_html_erb__393460728024828843_70155090220620'
```

**Comment by owen2345** [comment]
Fixed the problem!

**Comment by mazharoddin** [comment]
Thanks @owen2345, its working now.
