### ISSUE TITLE
undefined method when migrating cameleon1x 

### ISSUE THREAD

**Issue by kjj6198** [owen2345/camaleon-cms#209]
When I migrate version1x to 2, it comes up undefined method error. 

```
NoMethodError: undefined method `system_info' for PluginRoutes:Class
in camaleoncms_1xmigration-b9b734f2a7f9/config/routes.rb
```
it looks like the method `system_info` doesn't declare. I looks up the origin gem. The `system_info` method was defined in `lib/plugin_routes.rb` file. Should I also add original gem `camaleon_cms` in my gemfile? But the routes file would be declared twice, and the same name is already in use.

**Comment by kjj6198** [comment]
The problem is solved when I add gem `camaleon` in my gemfile.
```
gem "camaleon_cms"
gem "migration1x", github: 'owen2345/camaleoncms_1xmigration'
```
remember to update `camaleon_cms` by typing `bundle update` in terminal. And make sure your `lib/plugin_routes.rb` file was lastest version.

Now everything is working, thanks a lot. 👍👍👍
